# Generated by Django 3.1.2 on 2021-02-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonset',
            name='set_image',
        ),
        migrations.AddField(
            model_name='mainset',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
