# Generated by Django 3.1.1 on 2020-10-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='has_feedback',
        ),
        migrations.AddField(
            model_name='lesson',
            name='audio_record',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='audio_transcribe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='correct_feedback',
            field=models.TextField(default='Proceeding to the next lesson.'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='screen_record',
            field=models.BooleanField(default=False),
        ),
    ]
