# Generated by Django 3.0.8 on 2020-07-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reasoning',
            name='reasoning_type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('Text', 'Free Response'), ('Both', 'Multiple Choice and Free Response')], default='MC', max_length=4),
        ),
    ]
