# Generated by Django 3.0.7 on 2020-07-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reasoning',
            name='mc_set',
            field=models.ManyToManyField(blank=True, to='core.McChoice'),
        ),
    ]
