# Generated by Django 3.1.1 on 2020-09-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='reason',
            field=models.ManyToManyField(blank=True, null=True, to='core.Reasoning'),
        ),
    ]
