# Generated by Django 3.1.1 on 2020-09-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='algebra',
            field=models.CharField(default='Lesson To Go To', max_length=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='correct',
            field=models.CharField(default='Lesson To Go To', max_length=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='not_using_initial_value',
            field=models.CharField(default='Lesson To Go To', max_length=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='self_reference',
            field=models.CharField(default='Lesson To Go To', max_length=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='simplify',
            field=models.CharField(default='Lesson To Go To', max_length=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='syntax',
            field=models.CharField(default='Lesson To Go To', max_length=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='use_of_concrete_values',
            field=models.CharField(default='Lesson To Go To', max_length=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='variable',
            field=models.CharField(default='Lesson To Go To', max_length=50),
        ),
    ]
