# Generated by Django 3.1.7 on 2021-02-23 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='default',
        ),
    ]
