# Generated by Django 3.1.2 on 2020-10-16 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='simplify',
            new_name='SIM',
        ),
    ]
