# Generated by Django 3.1.6 on 2021-02-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainset',
            name='set_image',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
