# Generated by Django 3.1.1 on 2020-09-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200710_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reasoning',
            name='reasoning_type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('Text', 'Free Response'), ('Both', 'Multiple Choice and Free Response'), ('None', 'None')], default='MC', max_length=4),
        ),
    ]
