# Generated by Django 3.1.7 on 2021-02-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_lesson_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='default',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
