# Generated by Django 3.1.6 on 2021-02-22 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mainset_set_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainset',
            name='set_image',
        ),
    ]
