# Generated by Django 3.1.1 on 2020-09-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200924_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='reason',
            field=models.ManyToManyField(blank=True, to='core.Reasoning'),
        ),
    ]
