# Generated by Django 3.1.2 on 2020-10-16 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201016_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='algebra',
            new_name='ALG',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='not_using_initial_value',
            new_name='INIT',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='self_reference',
            new_name='NUM',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='use_of_concrete_values',
            new_name='SELF',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='variable',
            new_name='VAR',
        ),
    ]
