# Generated by Django 3.1.1 on 2020-09-29 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lesson_is_alternate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='incorrect_answers',
        ),
    ]
