# Generated by Django 3.1.1 on 2020-10-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lesson_is_alternate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='can_mutate',
            field=models.BooleanField(default=False),
        ),
    ]
