# Generated by Django 3.1.1 on 2020-09-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200904_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='number_of_attempts',
            field=models.IntegerField(default=1),
        ),
    ]
