# Generated by Django 3.1.2 on 2020-10-15 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lesson_can_mutate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='reason',
        ),
        migrations.AddField(
            model_name='lesson',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reasoning'),
        ),
    ]
