# Generated by Django 3.1.2 on 2021-02-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lesson_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonset',
            name='index_in_set',
            field=models.IntegerField(default=0),
        ),
    ]
