# Generated by Django 3.1.1 on 2020-09-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200913_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='instruction',
            field=models.TextField(default='Please complete the Confirm assertion(s) and check correctness.'),
        ),
    ]
