# Generated by Django 3.1.1 on 2020-12-07 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lessonset_set_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonset',
            name='first_in_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_in_set', to='core.lesson'),
        ),
    ]
