# Generated by Django 3.1.1 on 2020-09-13 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200913_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncorrectAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_text', models.CharField(default='Lesson2', max_length=200)),
                ('answer_type', models.CharField(choices=[('SIM', 'Simplify'), ('SELF', 'Self Reference'), ('NUM', 'Used Concrete Value as Answer'), ('INIT', 'Missing # Symbol'), ('ALG', 'Algebra'), ('VAR', 'Variable')], default='SIM', max_length=4)),
                ('answer_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='algebra',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='correct',
            field=models.CharField(default='Lesson To Go To', max_length=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='not_using_initial_value',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='self_reference',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='simplify',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='sub_lessons_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='use_of_concrete_values',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='variable',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='code',
            name='lesson_code',
            field=models.TextField(max_length=750),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='instruction',
            field=models.TextField(default='Please complete the Confirm assertion(s) and check correctness.'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reasoning'),
        ),
        migrations.AlterField(
            model_name='mcchoice',
            name='choice_text',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reasoning',
            name='reasoning_type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('Text', 'Free Response'), ('Both', 'Multiple Choice and Free Response'), ('None', 'None')], default='None', max_length=4),
        ),
        migrations.AddField(
            model_name='lesson',
            name='incorrect_answers',
            field=models.ManyToManyField(blank=True, to='core.IncorrectAnswer'),
        ),
    ]
