# Generated by Django 3.1.1 on 2020-09-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_lesson_incorrect_answers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IncorrectAnswer',
            new_name='Incorrect_answer',
        ),
        migrations.AddField(
            model_name='lesson',
            name='incorrect_answers',
            field=models.ManyToManyField(blank=True, to='core.Incorrect_answer'),
        ),
    ]
