# Generated by Django 3.1.1 on 2020-09-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lesson_number_of_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='sub_lessons_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='number_of_attempts',
            field=models.IntegerField(default=100),
        ),
    ]
