# Generated by Django 3.1.1 on 2020-10-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lesson_can_mutate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='has_feedback',
            field=models.BooleanField(default=False),
        ),
    ]
