# Generated by Django 3.1.8 on 2021-05-09 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_lesson_correct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='correct_key',
            new_name='correct',
        ),
    ]
