# Generated by Django 3.1.1 on 2020-09-29 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200929_0735'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Incorrect_answer',
            new_name='IncorrectAnswer',
        ),
    ]
