# Generated by Django 3.1.1 on 2020-10-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lesson_has_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='Try Again!', max_length=50)),
                ('feedback_type', models.CharField(choices=[('DEF', 'Default'), ('COR', 'Correct'), ('SIM', 'Simplify'), ('SELF', 'Self Reference'), ('NUM', 'Used Concrete Value as Answer'), ('INIT', 'Missing # Symbol'), ('ALG', 'Algebra'), ('VAR', 'Variable'), ('SUB', 'Sub_Lesson')], default='DEF', max_length=4)),
                ('feedback_text', models.TextField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='feedback',
            field=models.ManyToManyField(blank=True, to='core.Feedback'),
        ),
    ]
