# Generated by Django 3.1.1 on 2020-09-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200904_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incorrect_Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='lesson',
            name='number_of_attempts',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='lesson',
            name='simplify_answers',
            field=models.ManyToManyField(blank=True, to='core.Incorrect_Answers'),
        ),
    ]
