# Generated by Django 3.1.1 on 2020-12-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lessonset_first_in_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_walkthrough',
            field=models.BooleanField(default=False),
        ),
    ]
