# Generated by Django 3.1.2 on 2020-10-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201016_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='audio_record',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='audio_transcribe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='screen_record',
            field=models.BooleanField(default=False),
        ),
    ]
