# Generated by Django 3.1.8 on 2021-05-09 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210509_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonset',
            name='lessons',
        ),
        migrations.RemoveField(
            model_name='mainset',
            name='lessons',
        ),
    ]
