# Generated by Django 3.1.1 on 2020-09-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200929_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonset',
            name='number_normal_lessons',
            field=models.IntegerField(default=0),
        ),
    ]
