# Generated by Django 3.1.1 on 2020-09-05 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200905_1029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Incorrect_Answers',
            new_name='Incorrect_Answer',
        ),
    ]
