# Generated by Django 3.1.6 on 2021-02-22 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_mainset_set_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='default',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
