# Generated by Django 3.1.1 on 2020-09-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200905_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='syntax',
        ),
    ]
