# Generated by Django 3.1.1 on 2020-09-29 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_lessonset_number_normal_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonset',
            name='number_normal_lessons',
        ),
    ]
