# Generated by Django 3.1.8 on 2021-05-17 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210509_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonAlternate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Simplify'), (2, 'Self Reference'), (3, 'Use of Concrete Values'), (4, 'Not Using Initial Value'), (5, 'Algebra'), (6, 'Variable')])),
                ('alternate_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.lessonset')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lesson')),
            ],
        ),
    ]
