# Generated by Django 3.1.8 on 2021-05-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_lessonalternate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='algebra',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='default',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='is_alternate',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='not_using_initial_value',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='self_reference',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='simplify',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='sub_lessons_available',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='use_of_concrete_values',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='variable',
        ),
        migrations.AlterField(
            model_name='lessonalternate',
            name='type',
            field=models.IntegerField(choices=[(0, 'Default'), (1, 'Simplify'), (2, 'Self Reference'), (3, 'Used Concrete Value as Answer'), (4, 'Missing # Symbol'), (5, 'Algebra'), (6, 'Variable')]),
        ),
    ]
