# Generated by Django 3.1.1 on 2020-09-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200905_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='algebra_answers',
            field=models.ManyToManyField(blank=True, related_name='algebra_answers', to='core.Incorrect_Answer'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='not_using_initial_value_answers',
            field=models.ManyToManyField(blank=True, related_name='initial_answers', to='core.Incorrect_Answer'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='self_reference_answers',
            field=models.ManyToManyField(blank=True, related_name='self_answers', to='core.Incorrect_Answer'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='use_of_concrete_values_answers',
            field=models.ManyToManyField(blank=True, related_name='concrete_answers', to='core.Incorrect_Answer'),
        ),
    ]
