# Generated by Django 3.1.8 on 2021-05-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210517_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incorrectanswer',
            name='lesson_text',
        ),
        migrations.AddField(
            model_name='incorrectanswer',
            name='type',
            field=models.IntegerField(choices=[(0, 'Default'), (1, 'Simplify'), (2, 'Self Reference'), (3, 'Used Concrete Value as Answer'), (4, 'Missing # Symbol'), (5, 'Algebra'), (6, 'Variable')], default=-1),
            preserve_default=False,
        ),
    ]
