# Generated by Django 3.1.1 on 2020-09-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200905_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='incorrect_answer',
            name='answer_type',
            field=models.CharField(choices=[('SIM', 'Simplify'), ('SELF', 'Self Reference'), ('NUM', 'Used Concrete Value as Answer'), ('INIT', 'Missing # Symbol'), ('ALG', 'Algebra'), ('VAR', 'Variable')], default='SIM', max_length=4),
        ),
        migrations.AddField(
            model_name='incorrect_answer',
            name='lesson_text',
            field=models.CharField(default='Lesson2', max_length=200),
        ),
    ]
