# Generated by Django 3.1.8 on 2021-05-18 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210518_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incorrectanswer',
            name='answer_type',
        ),
    ]
