# Generated by Django 3.1.1 on 2020-09-05 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200905_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='number_of_attempts',
        ),
    ]
