# Generated by Django 3.1.8 on 2021-05-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210518_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonalternate',
            name='replace',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
