# Generated by Django 3.1.8 on 2021-05-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_feedback_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_type',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.IntegerField(choices=[(-1, 'Correct'), (0, 'Default'), (1, 'Simplify'), (2, 'Self Reference'), (3, 'Used Concrete Value as Answer'), (4, 'Missing # Symbol'), (5, 'Algebra'), (6, 'Variable')]),
        ),
        migrations.AlterField(
            model_name='lessonalternate',
            name='type',
            field=models.IntegerField(choices=[(-1, 'Correct'), (0, 'Default'), (1, 'Simplify'), (2, 'Self Reference'), (3, 'Used Concrete Value as Answer'), (4, 'Missing # Symbol'), (5, 'Algebra'), (6, 'Variable')]),
        ),
        migrations.AlterField(
            model_name='lessonincorrectanswers',
            name='type',
            field=models.IntegerField(choices=[(-1, 'Correct'), (0, 'Default'), (1, 'Simplify'), (2, 'Self Reference'), (3, 'Used Concrete Value as Answer'), (4, 'Missing # Symbol'), (5, 'Algebra'), (6, 'Variable')]),
        ),
    ]
