# Generated by Django 3.1.8 on 2021-05-18 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210518_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='type',
            new_name='feedback_type',
        ),
    ]
