# Generated by Django 3.1.8 on 2021-05-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210518_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.IntegerField(choices=[(0, 'Default'), (1, 'Simplify'), (2, 'Self Reference'), (3, 'Used Concrete Value as Answer'), (4, 'Missing # Symbol'), (5, 'Algebra'), (6, 'Variable')]),
        ),
        migrations.AlterField(
            model_name='lessonalternate',
            name='type',
            field=models.IntegerField(choices=[(0, 'Default'), (1, 'Simplify'), (2, 'Self Reference'), (3, 'Used Concrete Value as Answer'), (4, 'Missing # Symbol'), (5, 'Algebra'), (6, 'Variable')]),
        ),
        migrations.AlterField(
            model_name='lessonincorrectanswers',
            name='type',
            field=models.IntegerField(choices=[(0, 'Default'), (1, 'Simplify'), (2, 'Self Reference'), (3, 'Used Concrete Value as Answer'), (4, 'Missing # Symbol'), (5, 'Algebra'), (6, 'Variable')]),
        ),
    ]
