# Generated by Django 3.1.8 on 2021-05-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210518_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonincorrectanswers',
            name='answer_text',
            field=models.CharField(default='REPLACEME', max_length=200),
            preserve_default=False,
        ),
    ]
