# Generated by Django 3.1.8 on 2021-05-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_lessonincorrectanswers_answer_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonincorrectanswers',
            name='answer',
        ),
        migrations.DeleteModel(
            name='IncorrectAnswer',
        ),
    ]
