# Generated by Django 3.1.8 on 2021-05-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210519_0902'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LessonIncorrectAnswers',
            new_name='IncorrectAnswer',
        ),
    ]
