# Generated by Django 3.2.4 on 2021-06-04 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210519_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='correct',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_index',
        ),
        migrations.RemoveField(
            model_name='lessonset',
            name='first_in_set',
        ),
        migrations.RemoveField(
            model_name='lessonset',
            name='index_in_set',
        ),
    ]
