# Generated by Django 3.2.5 on 2021-08-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_lesson_correctexpression'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_parsons',
            field=models.BooleanField(default=False),
        ),
    ]
