# Generated by Django 3.2.4 on 2021-10-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_lesson_is_parsons'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='multi_confirms',
            field=models.BooleanField(default=False),
        ),
    ]
