# Generated by Django 3.2.4 on 2021-10-04 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_lesson_sortable_lines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='correctExpression',
        ),
    ]
