# Generated by Django 3.1.2 on 2021-02-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonlog',
            name='main_set_key',
        ),
        migrations.AddField(
            model_name='lessonlog',
            name='main_set_key',
            field=models.ManyToManyField(blank=True, to='core.MainSet'),
        ),
    ]
