# Generated by Django 3.1.8 on 2021-05-09 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LessonLog',
        ),
    ]
