# Generated by Django 3.1.7 on 2021-02-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonlog',
            old_name='lesson_index',
            new_name='current_lesson_index',
        ),
        migrations.AddField(
            model_name='lessonlog',
            name='next_lesson_index',
            field=models.IntegerField(default=0),
        ),
    ]
