# Generated by Django 3.1.2 on 2021-02-18 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mainset_show'),
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonlog',
            name='main_set_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mainset'),
        ),
    ]
