# Generated by Django 3.0.7 on 2020-06-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MC_Set',
            new_name='MC_Answers',
        ),
    ]
