# Generated by Django 3.0.7 on 2020-07-06 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodeTemplate',
        ),
        migrations.DeleteModel(
            name='LessonSet',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='lesson',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Reference',
        ),
    ]
