# Generated by Django 3.1.7 on 2021-02-24 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_auto_20210224_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonlog',
            name='next_lesson_index',
        ),
    ]
