# Generated by Django 3.0.3 on 2020-02-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200212_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='Activity',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='References',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
