# Generated by Django 3.1.2 on 2021-02-10 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('tutor', '0002_auto_20210206_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonlog',
            name='main_set_key',
        ),
        migrations.AddField(
            model_name='lessonlog',
            name='main_set_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mainset'),
        ),
    ]
