# Generated by Django 3.0.6 on 2020-06-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_userinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='user_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='user_name',
            field=models.TextField(),
        ),
    ]
