# Generated by Django 3.0.7 on 2020-06-25 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_auto_20200625_0942'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MC_Answers',
            new_name='MC_Set',
        ),
    ]
