# Generated by Django 3.1.7 on 2021-02-24 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_remove_lessonlog_next_lesson_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonlog',
            old_name='current_lesson_index',
            new_name='lesson_index',
        ),
    ]
