# Generated by Django 3.0.7 on 2020-06-30 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_auto_20200625_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=30)),
                ('lesson_code', models.TextField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_code',
        ),
        migrations.AddField(
            model_name='lesson',
            name='instruction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tutor.Instruction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='reason',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tutor.Reasoning'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='reference_set',
            field=models.ManyToManyField(to='tutor.Reference'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tutor.Code'),
            preserve_default=False,
        ),
    ]
