# Generated by Django 3.0.7 on 2020-06-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_auto_20200630_1010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodeTemplate',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='reason',
        ),
        migrations.AddField(
            model_name='lesson',
            name='reason',
            field=models.ManyToManyField(to='tutor.Reasoning'),
        ),
    ]
