# Generated by Django 3.0.7 on 2020-06-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_auto_20200630_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='reasoning',
            name='mc_set',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
