# Generated by Django 3.0.7 on 2020-06-30 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0007_auto_20200630_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reasoning',
            name='mc_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.MC_Set'),
        ),
    ]
