# Generated by Django 3.0.7 on 2020-06-30 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0008_auto_20200630_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reasoning',
            name='mc_set',
        ),
    ]
