# Generated by Django 3.0.7 on 2020-06-30 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0011_auto_20200630_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reasoning',
            name='mc_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutor.MC_Set'),
        ),
    ]
