# Generated by Django 3.0.7 on 2020-07-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0012_auto_20200630_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='reasoning',
            name='response_text',
            field=models.CharField(default='Enter default message', max_length=100),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='instruction',
            field=models.CharField(max_length=30),
        ),
        migrations.RemoveField(
            model_name='reasoning',
            name='mc_set',
        ),
        migrations.AddField(
            model_name='reasoning',
            name='mc_set',
            field=models.ManyToManyField(to='tutor.MC_Choice'),
        ),
    ]
