# Generated by Django 3.0.7 on 2020-07-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0014_auto_20200704_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reasoning',
            name='mc_set',
            field=models.ManyToManyField(blank=True, to='tutor.MC_Choice'),
        ),
    ]
