# Generated by Django 3.0.7 on 2020-07-04 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0016_auto_20200704_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='free_resp',
            name='question',
        ),
        migrations.DeleteModel(
            name='Instruction',
        ),
        migrations.RemoveField(
            model_name='mc_set',
            name='answer_set',
        ),
        migrations.RemoveField(
            model_name='mc_set',
            name='question',
        ),
        migrations.DeleteModel(
            name='Free_Resp',
        ),
        migrations.DeleteModel(
            name='MC_Set',
        ),
    ]
