# Generated by Django 3.0.7 on 2020-07-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0017_auto_20200704_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='record',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='instruction',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='reason',
            field=models.ManyToManyField(blank=True, to='tutor.Reasoning'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='reference_set',
            field=models.ManyToManyField(blank=True, to='tutor.Reference'),
        ),
    ]
