# Generated by Django 3.0.7 on 2020-07-05 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0018_auto_20200705_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reasoning',
            old_name='reasoning_text',
            new_name='reasoning_question',
        ),
    ]
