# Generated by Django 3.0.7 on 2020-07-05 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0019_auto_20200705_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='record',
            new_name='screen_record',
        ),
        migrations.RenameField(
            model_name='reasoning',
            old_name='reasoning_key',
            new_name='reasoning_name',
        ),
        migrations.RemoveField(
            model_name='reasoning',
            name='free_response_text',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='reason',
        ),
        migrations.AddField(
            model_name='lesson',
            name='reason',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='tutor.Reasoning'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reasoning',
            name='reasoning_type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('Text', 'Text Response'), ('Both', 'Multiple Choice and Free Response')], default='MC', max_length=4),
        ),
    ]
