# Generated by Django 3.0.8 on 2020-07-05 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0020_auto_20200705_1020'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MC_Choice',
            new_name='McChoice',
        ),
    ]
