# Generated by Django 3.0 on 2019-12-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeginToReason', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='name',
            new_name='lesson_name',
        ),
        migrations.RenameField(
            model_name='references',
            old_name='key',
            new_name='reference_key',
        ),
        migrations.RenameField(
            model_name='references',
            old_name='reference',
            new_name='reference_text',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='reference',
        ),
        migrations.AddField(
            model_name='references',
            name='lesson',
            field=models.ManyToManyField(to='BeginToReason.Lesson'),
        ),
    ]
