# Generated by Django 3.0 on 2019-12-22 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BeginToReason', '0002_auto_20191222_1644'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='References',
            new_name='Reference',
        ),
    ]
