# Generated by Django 3.1.2 on 2020-10-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalog',
            name='past_answers',
            field=models.TextField(default='null'),
        ),
    ]
