# Generated by Django 3.1.2 on 2021-02-10 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('data_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalog',
            name='main_set_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mainset'),
        ),
    ]
