# Generated by Django 3.0.8 on 2020-07-31 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logdata',
            old_name='user_information_key',
            new_name='user_key',
        ),
    ]
