# Generated by Django 3.1.8 on 2021-04-13 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0004_auto_20210413_1031'),
        ('data_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalog',
            name='class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='educator.class'),
        ),
    ]
