# Generated by Django 3.1.2 on 2021-02-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0002_datalog_main_set_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalog',
            name='original_code',
            field=models.TextField(default='null'),
        ),
    ]
