# Generated by Django 3.1.2 on 2020-11-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0002_datalog_past_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalog',
            name='original_code',
            field=models.TextField(default='null'),
        ),
    ]
