# Generated by Django 3.0.8 on 2020-07-31 18:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200710_1113'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_analysis', '0002_auto_20200731_1215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogData',
            new_name='DataLog',
        ),
    ]
