# Generated by Django 3.0.8 on 2020-08-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0003_auto_20200731_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalog',
            name='code',
            field=models.TextField(default='null'),
        ),
    ]
