# Generated by Django 3.1.8 on 2021-05-09 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0004_datalog_assignment_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datalog',
            name='class_key',
        ),
        migrations.RemoveField(
            model_name='datalog',
            name='main_set_key',
        ),
    ]
