# Generated by Django 3.0.8 on 2020-08-01 15:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0004_datalog_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
