# Generated by Django 3.0.8 on 2020-08-01 15:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0005_auto_20200801_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalog',
            name='id',
            field=models.UUIDField(default=uuid.UUID('59fd8439-ab0f-41fa-9764-af184c79a47a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
