# Generated by Django 3.0.8 on 2020-08-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0007_auto_20200801_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalog',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
