# Generated by Django 3.0.8 on 2020-08-01 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0008_auto_20200801_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datalog',
            old_name='id',
            new_name='submission_id',
        ),
    ]
