# Generated by Django 3.0.8 on 2020-08-01 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0010_auto_20200801_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datalog',
            old_name='submission_id',
            new_name='id',
        ),
    ]
