# Generated by Django 3.0.3 on 2020-02-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_name',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_code',
        ),
        migrations.AddField(
            model_name='lesson',
            name='Code',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='Concept',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
