# Generated by Django 3.0.6 on 2020-05-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=320)),
                ('user_id', models.IntegerField(max_length=30)),
                ('user_name', models.TextField(max_length=30)),
            ],
        ),
    ]
