# Generated by Django 3.0.3 on 2020-02-14 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200212_1351'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Code_Template',
        ),
        migrations.DeleteModel(
            name='Reference',
        ),
    ]
