# Generated by Django 3.0.7 on 2020-06-08 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200601_1307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInformation',
        ),
    ]
