# Generated by Django 3.0 on 2019-12-24 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191224_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_code',
            field=models.TextField(max_length=500),
        ),
    ]
