# Generated by Django 3.0 on 2019-12-24 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191224_1512'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Code_Template',
        ),
    ]
