# Generated by Django 3.0.1 on 2019-12-26 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_lesson_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='template',
        ),
    ]
