# Generated by Django 3.0.7 on 2020-06-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('user_name', models.TextField()),
                ('user_school', models.CharField(max_length=50)),
                ('user_class', models.CharField(max_length=50)),
                ('user_gender', models.CharField(max_length=50)),
                ('user_race', models.CharField(max_length=50)),
                ('user_test', models.CharField(max_length=50)),
            ],
        ),
    ]
