# Generated by Django 3.1.2 on 2021-01-02 20:17

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='completed',
            field=models.ManyToManyField(blank=True, related_name='new_set', to='core.LessonSet'),
        ),

    ]
