# Generated by Django 3.1.2 on 2021-02-20 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='user_instructor',
        ),
    ]
