# Generated by Django 3.1.2 on 2021-02-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='current_main_set',
        ),
        migrations.AddField(
            model_name='userinformation',
            name='current_main_set',
            field=models.ManyToManyField(blank=True, null=True, to='core.MainSet'),
        ),
    ]
