# Generated by Django 3.0.7 on 2020-06-17 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 12, 0, 39, 915230)),
        ),
    ]
