# Generated by Django 3.1 on 2020-08-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='completed_lesson_index',
            field=models.IntegerField(default=0),
        ),
    ]
