# Generated by Django 3.1.2 on 2021-02-18 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mainset_show'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='in_progress_sets',
            field=models.ManyToManyField(blank=True, related_name='current_set', to='core.LessonSet'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='completed_sets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sets_completed', to='core.mainset'),
        ),
    ]
