# Generated by Django 3.1.1 on 2020-09-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='current_lesson_name',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
