# Generated by Django 3.1.8 on 2021-04-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='user_class',
        ),
        migrations.AddField(
            model_name='userinformation',
            name='user_classes',
            field=models.ManyToManyField(blank=True, related_name='members', to='instructor.Class'),
        ),
    ]
