# Generated by Django 3.1.1 on 2020-09-21 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('accounts', '0002_userinformation_current_lesson_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='completed_sets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sets_completed', to='core.lessonset'),
        ),
    ]
