# Generated by Django 3.1.2 on 2021-01-02 20:24

from django.db import migrations

def forward(apps, schema_editor):
    userinformation = apps.get_model("accounts", "userinformation")
    for user in userinformation.objects.all():
        user.completed.add(user.completed_sets)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userinformation_completed'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
