# Generated by Django 3.1.2 on 2021-03-31 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210331_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.CharField(default='', max_length=100, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='School'),
        ),
    ]
