# Generated by Django 3.0.7 on 2020-06-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userinformation_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='user_school',
            field=models.CharField(choices=[('Clem', 'Clemson'), ('FAU', 'FAU'), ('RHIT', 'RHIT'), ('Other', 'Other')], default='Other', max_length=10),
        ),
    ]
