# Generated by Django 3.1.2 on 2021-02-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('accounts', '0002_auto_20210206_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='current_main_set',
            field=models.ManyToManyField(blank=True, to='core.MainSet'),
        ),
    ]
