# Generated by Django 3.1.2 on 2021-02-18 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210218_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='in_progress_sets',
        ),
    ]
