# Generated by Django 3.0.7 on 2020-06-17 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200617_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 12, 19, 30, 278473)),
        ),
    ]
