# Generated by Django 3.0.7 on 2020-06-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userinformation_user_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='user_class',
            field=models.CharField(choices=[('CPSC2150', 'CPSC2150'), ('CPSC3720', 'CPSC3720'), ('Other', 'Other')], default='Other', max_length=10),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='user_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer Not To Answer', 'Prefer Not To Answer')], default='Prefer Not To Answer', max_length=25),
        ),
    ]
