# Generated by Django 3.0.7 on 2020-06-17 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200617_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='date_joined',
        ),
    ]
