# Generated by Django 3.1.2 on 2021-01-02 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210102_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='completed_sets',
        ),
    ]
