# Generated by Django 3.1.8 on 2021-04-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210420_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='user_instructor',
            field=models.BooleanField(default=False),
        ),
    ]
