# Generated by Django 3.1.2 on 2021-01-02 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userinformation_completed_sets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='completed',
            new_name='completed_sets',
        ),
    ]
