# Generated by Django 3.1.2 on 2021-02-10 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('accounts', '0004_auto_20210209_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='completed_sets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sets_completed', to='core.mainset'),
        ),
    ]
