# Generated by Django 3.1.8 on 2021-05-09 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userinformation_user_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='completed_lesson_index',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='completed_sets',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='current_lesson_index',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='current_lesson_name',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='current_lesson_set',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='current_main_set',
        ),
    ]
