# Generated by Django 3.1.1 on 2020-09-21 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200921_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='mood',
        ),
    ]
