# Generated by Django 3.1.1 on 2020-09-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userinformation_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='mood',
            field=models.CharField(choices=[('NEU', 'neutral'), ('HAP', 'happy'), ('EXC', 'excited'), ('UPS', 'upset'), ('SAD', 'sad')], default='NEU', max_length=3),
        ),
    ]
