# Generated by Django 3.1.2 on 2021-01-13 16:59

from django.db import migrations

def forward(apps, schema_editor):
    userinformation = apps.get_model("accounts", "userinformation")
    for user in userinformation.objects.all():
        user.current_lesson_sets.add(user.current_lesson_set)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userinformation_current_lesson_sets'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
