# Generated by Django 3.0.7 on 2020-06-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200611_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='user_class',
            field=models.CharField(choices=[('', ''), ('CPSC2150', 'CPSC2150'), ('CPSC3720', 'CPSC3720'), ('Other', 'Other')], default='Other', max_length=10),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='user_gender',
            field=models.CharField(choices=[('', ''), ('Male', 'Male'), ('Female', 'Female'), ('Prefer Not To Answer', 'Prefer Not To Answer')], default='Prefer Not To Answer', max_length=25),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='user_race',
            field=models.CharField(choices=[('', ''), ('American Indian or Alaska Native', 'American Indian or Alaska Native'), ('Asian', 'Asian'), ('Black or African American', 'Black or African American'), ('Hispanic or Latino', 'Hispanic or Latino'), ('Native Hawaiian or Other Pacific Islander', 'Native Hawaiian or Other Pacific Islander'), ('White', 'White'), ('Prefer Not To Answer', 'Prefer Not To Answer')], default='Prefer Not To Answer', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='user_school',
            field=models.CharField(choices=[('', ''), ('Clem', 'Clemson'), ('FAU', 'FAU'), ('RHIT', 'RHIT'), ('Other', 'Other')], default='Other', max_length=10),
        ),
    ]
