# Generated by Django 3.1.2 on 2021-01-13 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210113_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='current_lesson_set',
        ),
    ]
