# Generated by Django 3.0.7 on 2020-06-12 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200611_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 12, 18, 23, 28, 569827)),
        ),
    ]
