# Generated by Django 3.1.2 on 2021-01-13 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_userinformation_current_lesson_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='current_lesson_sets',
            new_name='current_lesson_set',
        ),
    ]
