# Generated by Django 3.0.7 on 2020-06-17 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userinformation_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 11, 48, 4, 532853)),
        ),
    ]
