# Generated by Django 3.1.2 on 2021-01-13 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('accounts', '0009_auto_20210113_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='current_lesson_sets',
            field=models.ManyToManyField(blank=True, related_name='current_set', to='core.LessonSet'),
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='current_lesson_set',
        ),
        migrations.AddField(
            model_name='userinformation',
            name='current_lesson_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lessonset'),
        ),
    ]
