# Generated by Django 3.1.1 on 2020-09-24 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200921_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='mood',
        ),
    ]
