# Generated by Django 3.1.1 on 2020-09-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_userinformation_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='mood',
            field=models.CharField(blank=True, choices=[('NEU', 'neutral'), ('HAP', 'happy'), ('EXC', 'excited'), ('UPS', 'upset'), ('SAD', 'sad')], max_length=3),
        ),
    ]
