# Generated by Django 3.1.2 on 2021-01-13 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210113_1207'),
    ]

    operations = [
    ]
