# Generated by Django 3.1.1 on 2020-09-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userinformation_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='mood',
            field=models.CharField(default='neutral', max_length=10),
        ),
    ]
