# Generated by Django 3.1.2 on 2021-01-13 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210113_1208'),
    ]

    operations = [
    ]
