# Generated by Django 3.1.2 on 2021-01-13 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210113_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='current_lesson_sets',
            new_name='in_progress_sets',
        ),
    ]
