# Generated by Django 3.1.2 on 2021-01-13 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210113_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='current_lesson_sets',
        ),
    ]
