# Generated by Django 3.1.2 on 2021-01-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('accounts', '0015_remove_userinformation_current_lesson_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='current_lesson_sets',
            field=models.ManyToManyField(blank=True, related_name='current_set', to='core.LessonSet'),
        ),
    ]
