# Generated by Django 3.0 on 2019-12-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeginToReason', '0003_auto_20191222_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_code',
            field=models.TextField(default='test', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reference',
            name='lesson',
            field=models.ManyToManyField(related_name='references', to='BeginToReason.Lesson'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='reference_text',
            field=models.TextField(max_length=250),
        ),
    ]
