# Generated by Django 3.0 on 2019-12-24 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BeginToReason', '0005_auto_20191224_1508'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Template',
            new_name='Code_Template',
        ),
    ]
