# Generated by Django 3.0 on 2019-12-25 20:49

import BeginToReason.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BeginToReason', '0009_lesson_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BeginToReason.Code_Template'),
        
        ),
    ]
