# Generated by Django 3.0 on 2019-12-26 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BeginToReason', '0010_auto_20191225_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='template',
        ),
    ]
