# Generated by Django 3.0 on 2019-12-26 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BeginToReason', '0011_remove_lesson_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BeginToReason.Code_Template'),
            preserve_default=False,
        ),
    ]
