# Generated by Django 3.1.8 on 2021-04-13 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('instructor', '0002_auto_20210412_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='lesson_sets',
            field=models.ManyToManyField(blank=True, related_name='classes', to='core.MainSet'),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Name'),
        ),
    ]
