# Generated by Django 3.1.8 on 2021-04-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('instructor', '0003_auto_20210413_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='lesson_sets',
            field=models.ManyToManyField(blank=True, related_name='classes', to='core.LessonSet'),
        ),
    ]
