# Generated by Django 3.1.8 on 2021-04-20 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0006_classmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='join_code',
            field=models.CharField(default=123456, max_length=6, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Join_Code'),
            preserve_default=False,
        ),
    ]
