# Generated by Django 3.1.8 on 2021-04-20 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0007_class_join_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='join_code',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Join_Code'),
        ),
    ]
