# Generated by Django 3.1.8 on 2021-05-11 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0013_auto_20210511_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternateprogress',
            name='assignment_key',
        ),
        migrations.RemoveField(
            model_name='alternateprogress',
            name='user_info_key',
        ),
        migrations.AddField(
            model_name='alternateprogress',
            name='progress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='instructor.assignmentprogress'),
        ),
    ]
