# Generated by Django 3.2.9 on 2021-11-23 05:03

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Name')),
                ('join_code', models.CharField(max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Join_Code')),
            ],
        ),
        migrations.CreateModel(
            name='ClassMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_educator', models.BooleanField(default=False)),
                ('class_taking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educator.class')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userinformation')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_set_index', models.IntegerField(default=0)),
                ('current_lesson_index', models.IntegerField(default=0)),
                ('assignment_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educator.assignment')),
                ('user_info_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userinformation')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='class_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educator.class'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='main_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mainset'),
        ),
        migrations.CreateModel(
            name='AlternateProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_lesson_index', models.IntegerField(default=0)),
                ('alternate_level', models.IntegerField(default=0)),
                ('lesson_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lessonset')),
                ('progress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='educator.assignmentprogress')),
            ],
        ),
    ]
