# Generated by Django 3.1.2 on 2021-03-31 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
    ]
