# Generated by Django 3.1.8 on 2021-04-20 14:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('educator', '0008_auto_20210420_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='main_sets',
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True)),
                ('class_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educator.class')),
                ('main_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mainset')),
            ],
        ),
    ]
